package rss.formatter

enum class RssFormatToken(val value: String) {
    ITEM_AUTHOR("{{ITEM_AUTHOR}}"),
    ITEM_CATEGORY("{{ITEM_CATEGORY}}"),
    ITEM_DESCRIPTION("{{ITEM_DESCRIPTION}}"),
    ITEM_PUBLISHED_DATE("{{ITEM_PUBLISHED_DATE}}"),
    ITEM_UPDATED_DATE("{{ITEM_UPDATED_DATE}}"),
    ITEM_URL("{{ITEM_URL}}"),
    ITEM_TITLE("{{ITEM_TITLE}}"),
    CHANNEL_CATEGORY("{{CHANNEL_CATEGORY}}"),
    CHANNEL_COPYRIGHT("{{CHANNEL_COPYRIGHT}}"),
    CHANNEL_DESCRIPTION("{{CHANNEL_DESCRIPTION}}"),
    CHANNEL_GENERATOR("{{CHANNEL_GENERATOR}}"),
    CHANNEL_LANGUAGE("{{CHANNEL_LANGUAGE}}"),
    CHANNEL_LAST_BUILD_DATE("{{CHANNEL_LAST_BUILD_DATE}}"),
    CHANNEL_MANAGING_EDITOR("{{CHANNEL_MANAGING_EDITOR}}"),
    CHANNEL_PUBLISHED_DATE("{{CHANNEL_PUBLISHED_DATE}}"),
    CHANNEL_TITLE("{{CHANNEL_TITLE}}"),
    CHANNEL_TTL("{{CHANNEL_TTL}}"),
    CHANNEL_URL("{{CHANNEL_URL}}"),
    CHANNEL_WEB_MASTER("{{CHANNEL_WEB_MASTER}}"),
    CHANNEL_IMAGE_DESCRIPTION("{{CHANNEL_IMAGE_DESCRIPTION}}"),
    CHANNEL_IMAGE_HEIGHT("{{CHANNEL_IMAGE_HEIGHT}}"),
    CHANNEL_IMAGE_LINK("{{CHANNEL_IMAGE_LINK}}"),
    CHANNEL_IMAGE_TITLE("{{CHANNEL_IMAGE_TITLE}}"),
    CHANNEL_IMAGE_URL("{{CHANNEL_IMAGE_URL}}"),
    CHANNEL_IMAGE_WIDTH("{{CHANNEL_IMAGE_WIDTH}}");

    override fun toString(): String {
        return value;
    }
}
